#cache:
#  directories:
#    - $HOME/.m2
language: java

jdk: openjdk8

name: Codecov
uses: codecov/codecov-action@v3.0.0


sudo: false
script:
  - mvn clean
  - mvn evosuite:generate
  - mvn evosuite:export
#  - mvn test jacoco:report
#  - mvn test jacoco:report coveralls:report
  - bash <(curl -s https://codecov.io/bash)
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov ./codecov



#after_success: