#cache:
#  directories:
#    - $HOME/.m2
language: java

jdk: openjdk8

name: Codecov
uses: codecov/codecov-action@v3.0.0


sudo: false
script:
  - java -version
  - mvn clean install
  - mvn clean package
  - mvn -Dcores=2 evosuite:generate
  - mvn evosuite:export
  - mvn test
  - bash <(curl -s https://codecov.io/bash)
#  - curl -Os https://uploader.codecov.io/latest/linux/codecov
#  - chmod +x codecov ./codecov



#after_success: